repo_url: https://github.com/vitorfleonardo/VerificAAA
repo_name: VerificAAA

site_url: https://github.com/vitorfleonardo/VerificAAA
site_name: VerificAAA

use_directory_urls: False

nav:
  - Início: 'index.md'
  - Checklist: 'checklist.md'
  - Bibliografia: 'bibliografia.md'

  - Desenvolvimento Web:
    - Acessibilidade Web: 'devWeb/web.md'
    - Desenvolvimento: 'devWeb/non_text_content.md'

  - Design:
    - Design: 'design/design.md'
  
  - Geração de Conteúdo:
    - Conteúdo: 'geracaoConteudo/conteudo.md'

  - Gestão de Projetos:
    - Primeiro Passo: 'gestaoProjeto/primeiroP.md'
    - Conscientização: 'gestaoProjeto/conscientizacao.md'
    - Planejamento: 'gestaoProjeto/planejamento.md'

theme:
  name: readthedocs
  locale: pt_BR
  titles_only: true

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
