repo_url: https://github.com/vitorfleonardo/AccessibilityChecker
repo_name: AccessibilityChecker

site_name: VerificAAA

theme:
  name: readthedocs

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

nav:
- Início: "index.md"
- Gestão de Projetos:
  - Primeiro: "primeiro.md"

