repo_url: https://github.com/vitorfleonardo/VerificAAA
repo_name: VerificAAA

site_name: VerificAAA

theme:
  name: readthedocs

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

nav:
  - Início: "index.md"
  - Gestão de Projetos:
    - Primeiro: "gestaoProjetos/primeiro.md"

